### ISSUE TITLE
Необходимо обрабатывать исключения при значениях `size`, превышающих максимальную длительность сигнала

### ISSUE THREAD

**Issue by Tecatech** [aeshcherbakova/mephi_3sem_labs#1]
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/29de7dd8cf7a02ab7e6d959f42b21950ffa4c2ea/lab3/Static/TimeDiagram_static.cpp#L72

**Comment by aeshcherbakova** [comment]
Добавлена проверка на положительность size и ограничение максимальной длительности - при превышении сигнал будет обрезан. 
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/eadf5e310eba1472f69cc86b1afa6e4dad2134b8/lab3/Static/TimeDiagram_static.cpp#L71
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/eadf5e310eba1472f69cc86b1afa6e4dad2134b8/lab3/Static/TimeDiagram_static.cpp#L72
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/eadf5e310eba1472f69cc86b1afa6e4dad2134b8/lab3/Static/TimeDiagram_static.cpp#L75
