### ISSUE TITLE
Нет необходимости в поиске исключений

### ISSUE THREAD

**Issue by Tecatech** [aeshcherbakova/mephi_3sem_labs#2]
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/29de7dd8cf7a02ab7e6d959f42b21950ffa4c2ea/lab3/Static/TimeDiagram_static.cpp#L325

https://github.com/aeshcherbakova/mephi_3sem_labs/blob/29de7dd8cf7a02ab7e6d959f42b21950ffa4c2ea/lab3/Static/TimeDiagram_static.cpp#L302

**Comment by aeshcherbakova** [comment]
Исправлено.
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/eadf5e310eba1472f69cc86b1afa6e4dad2134b8/lab3/Static/TimeDiagram_static.cpp#L333
