### ISSUE TITLE
Стоит увеличить размер массива сигналов, чтобы не выходить за пределы максимальной длительности

### ISSUE THREAD

**Issue by Tecatech** [aeshcherbakova/mephi_3sem_labs#3]
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/29de7dd8cf7a02ab7e6d959f42b21950ffa4c2ea/lab3/Static/TimeDiagram_static.cpp#L213

**Comment by aeshcherbakova** [comment]
Размер временного массива сигналов увеличен.
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/551cc6ab320fca07bc531bd39d5ce05fde49b30c/lab3/Static/TimeDiagram_static.cpp#L214
 Не выхождение за пределы максимальной длительности в диаграмме-результате сложения обеспечивается в конструкторе (см. issue #1 ).
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/551cc6ab320fca07bc531bd39d5ce05fde49b30c/lab3/Static/TimeDiagram_static.cpp#L228
