### ISSUE TITLE
Возможно, стоит добавить аналогичную проверку для первой диаграммы?

### ISSUE THREAD

**Issue by Tecatech** [aeshcherbakova/mephi_3sem_labs#4]
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/29de7dd8cf7a02ab7e6d959f42b21950ffa4c2ea/lab3/Static/TimeDiagram_static.cpp#L212

**Comment by aeshcherbakova** [comment]
Добавлено.
https://github.com/aeshcherbakova/mephi_3sem_labs/blob/551cc6ab320fca07bc531bd39d5ce05fde49b30c/lab3/Static/TimeDiagram_static.cpp#L211
